### ISSUE TITLE
Items doesn't flash before despawning

### ISSUE THREAD

**Issue by EGOIST1372** [StrikerRockers-Mods/ClearDespawn-Fabric#8]
Items doesn't flash before despawning. it might be because one of my mods idk but I have many mods (screenshot)
All config values are default.
![image](https://user-images.githubusercontent.com/86555131/167231953-e33b7c12-1a1e-4060-acfa-9ac413643bc7.png)

also why time until item despawn option is 6000? if its in seconds why its not vanilla 300 seconds? just curious cause items despawn in 300 seconds but what is 6000?

**Comment by strikerrocker** [comment]
despawnTime is in ticks instead of seconds as mods can manipulate it more accurately so I am giving the option for it. Also that's a lot of mods I would recommend following 
![image](https://user-images.githubusercontent.com/28724985/168108122-38958759-98dc-4f07-b5df-f2a0670fefdc.png)
to find the mod which causes the issue if you don't mind.

**Comment by EGOIST1372** [comment]
Too lazy to do it tbh
sorry ;-;

**Comment by EGOIST1372** [comment]
Update: 
It still not flashing in 1.19 and my mods number increased even more :D
IDK which mod cause this
